"""
Generates the Store/MSIX logo assets that `packaging/msix/AppxManifest.xml` references,
from the single brand PNG in `assets/images/`.

Nothing under `packaging/msix/assets/` is committed: it is all derived from one source
image, so it is gitignored and regenerated by `build_msix.ps1` before every pack. The
manifest, this script and `tests/test_msix_packaging.py` agree on the file names -- the
test asserts that every path the manifest references is actually produced here, at the
pixel size the name claims.

The brand PNG is 500x500, which is smaller than several of the sizes Windows asks for (the
200%/400% tiles, the 256 px icon). Those variants are genuine upscales and will look soft;
the script names each one it had to upscale rather than quietly shipping a blurry tile, and
`docs/MICROSOFT_STORE.md` records it as an open defect wanting a bigger master image, not
as something already solved.
"""

import argparse
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = REPO_ROOT / "assets" / "images" / "ToneSphere.png"
DEFAULT_OUTPUT = Path(__file__).resolve().parent / "assets"

# The scale factors Windows resolves a tile/icon reference against. The manifest points at
# the unqualified name (`Square150x150Logo.png`); that file is the 100% form and doubles as
# the neutral resource MRT falls back to, and the `.scale-NNN` siblings are what a
# higher-DPI display actually picks up.
SCALES = (125, 150, 200, 400)

# Square44x44Logo is the one asset Windows also wants at fixed pixel sizes rather than at
# scale factors: the taskbar, Alt-Tab and the Start app list choose a `targetsize` variant.
# The `altform-unplated` form is the same artwork drawn without the accent-coloured
# backplate behind it, which is the form the taskbar uses.
TARGET_SIZES = (16, 24, 32, 48, 256)


@dataclass(frozen=True)
class Logo:
    name: str
    width: int
    height: int
    # Fraction of the tile's shorter side the artwork occupies. Icons fill their box; tiles
    # do not -- Windows' own tile templates inset the artwork, and artwork bled to the tile
    # edge is the most obvious sign of a logo set generated by resizing alone.
    artwork_fraction: float


LOGOS = (
    Logo("StoreLogo", 50, 50, 1.0),
    Logo("Square44x44Logo", 44, 44, 1.0),
    Logo("Square71x71Logo", 71, 71, 0.66),
    Logo("Square150x150Logo", 150, 150, 0.66),
    Logo("Square310x310Logo", 310, 310, 0.66),
    Logo("Wide310x150Logo", 310, 150, 0.66),
)


def _render(source: Image.Image, width: int, height: int, artwork_fraction: float) -> tuple[Image.Image, bool]:
    box = round(min(width, height) * artwork_fraction)
    ratio = min(box / source.width, box / source.height)
    artwork_size = (max(1, round(source.width * ratio)), max(1, round(source.height * ratio)))

    canvas = Image.new("RGBA", (width, height), (0, 0, 0, 0))
    artwork = source.resize(artwork_size, Image.LANCZOS)
    canvas.alpha_composite(artwork, ((width - artwork_size[0]) // 2, (height - artwork_size[1]) // 2))

    upscaled = artwork_size[0] > source.width or artwork_size[1] > source.height
    return canvas, upscaled


def _variants() -> list[tuple[str, int, int, float]]:
    """Every (filename, width, height, artwork_fraction) the manifest and the pack expect."""
    variants: list[tuple[str, int, int, float]] = []

    for logo in LOGOS:
        variants.append((f"{logo.name}.png", logo.width, logo.height, logo.artwork_fraction))
        for scale in SCALES:
            variants.append((
                f"{logo.name}.scale-{scale}.png",
                round(logo.width * scale / 100),
                round(logo.height * scale / 100),
                logo.artwork_fraction,
            ))

    for size in TARGET_SIZES:
        variants.append((f"Square44x44Logo.targetsize-{size}.png", size, size, 1.0))
        variants.append((f"Square44x44Logo.targetsize-{size}_altform-unplated.png", size, size, 1.0))

    return variants


def expected_assets() -> dict[str, tuple[int, int]]:
    """Filename to (width, height), for anything that needs to check the set without generating it."""
    return {name: (width, height) for name, width, height, _ in _variants()}


def generate(source_path: Path = DEFAULT_SOURCE, output_dir: Path = DEFAULT_OUTPUT) -> tuple[list[Path], list[str]]:
    """
    Writes every logo variant into `output_dir`.

    Returns the paths written and the names of the variants whose artwork had to be upscaled
    past the source image's own resolution.
    """
    if not source_path.is_file():
        raise FileNotFoundError(f"brand image not found: {source_path}")

    output_dir.mkdir(parents=True, exist_ok=True)

    with Image.open(source_path) as opened:
        source = opened.convert("RGBA")

    written: list[Path] = []
    upscaled: list[str] = []

    for name, width, height, fraction in _variants():
        image, was_upscaled = _render(source, width, height, fraction)
        destination = output_dir / name
        image.save(destination, format="PNG", optimize=True)
        written.append(destination)
        if was_upscaled:
            upscaled.append(name)

    return written, upscaled


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate the MSIX/Store logo set for ToneSphere.")
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE, help="brand PNG to derive the logos from")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT, help="directory to write the logo set into")
    args = parser.parse_args()

    written, upscaled = generate(args.source, args.output)

    with Image.open(args.source) as opened:
        source_width, source_height = opened.size

    print(f"{len(written)} assets written to {args.output}")
    print(f"source: {args.source} ({source_width}x{source_height})")

    if upscaled:
        print(
            f"\n{len(upscaled)} variants are upscaled past the {source_width}x{source_height} source and will look"
            " soft. Replace the source with a 1024x1024-or-larger master before submitting:"
        )
        for name in upscaled:
            print(f"  {name}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
